server:
  port: 8188
  servlet:
    context-path: /hibernate

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
      jpa:
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect